services:
  api-ideas:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
